fails:Executing break from within a block returns from the original invoking method even in case of chained calls
fails:Executing break from within a block runs ensures when continuing upward
fails:Executing break from within a block doesn't run ensures in the destination method
